"""
Django settings for analytics_backend project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Add these at the top of your settings.py
import os
from dotenv import load_dotenv
from urllib.parse import urlparse, parse_qsl

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-1%vtl=_i8gjig+!@f2ofw-j*_=2h(q0=8en98@(#!l&bac^uo6'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1', '.vercel.app']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'marketplace_analytics.apps.MarketplaceAnalyticsConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'analytics_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'analytics_backend.wsgi.app'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# Replace the DATABASES section of your settings.py with this
tmpMarketplacePostgres = urlparse(os.getenv("MARKETPLACE_DATABASE_URL"))
tmpAnalyticsPostgres = urlparse(os.getenv("ANALYTICS_DATABASE_URL"))

DATABASES = {
    'marketplace': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': tmpMarketplacePostgres.path.replace('/', ''),
        'USER': tmpMarketplacePostgres.username,
        'PASSWORD': tmpMarketplacePostgres.password,
        'HOST': tmpMarketplacePostgres.hostname,
        'PORT': 5432,
        'OPTIONS': dict(parse_qsl(tmpMarketplacePostgres.query)),
    },
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': tmpAnalyticsPostgres.path.replace('/', ''),
        'USER': tmpAnalyticsPostgres.username,
        'PASSWORD': tmpAnalyticsPostgres.password,
        'HOST': tmpAnalyticsPostgres.hostname,
        'PORT': 5432,
        'OPTIONS': dict(parse_qsl(tmpAnalyticsPostgres.query)),
    }
}

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
