# Generated by Django 6.0.2 on 2026-03-18 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('app_startup', 'App Startup'), ('screen_navigation', 'Screen Navigation')], max_length=30)),
                ('device_model', models.CharField(max_length=100)),
                ('platform', models.CharField(choices=[('android', 'Android'), ('ios', 'iOS')], max_length=10)),
                ('duration_ms', models.FloatField(help_text='Duration in milliseconds')),
                ('timestamp', models.DateTimeField()),
                ('app_version', models.CharField(blank=True, default='', max_length=20)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['event_type', 'timestamp'], name='marketplace_event_t_7bcba3_idx'), models.Index(fields=['device_model'], name='marketplace_device__117225_idx')],
            },
        ),
    ]
