# Generated by Django 6.0.2 on 2026-03-18 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace_analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='performanceevent',
            name='os_version',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
