# Generated by Django 6.0.2 on 2026-03-18 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace_analytics', '0002_performanceevent_os_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(choices=[('listing_viewed', 'Listing Viewed'), ('chat_started', 'Chat Started'), ('first_message_sent', 'First Message Sent'), ('transaction_completed', 'Transaction Completed')], db_index=True, max_length=50)),
                ('listing_id', models.BigIntegerField(db_index=True)),
                ('buyer_user_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('seller_user_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('occurred_at', models.DateTimeField(db_index=True)),
                ('ingested_at', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('client_event_id', models.CharField(blank=True, max_length=64, null=True, unique=True)),
            ],
            options={
                'ordering': ['-occurred_at', '-id'],
                'indexes': [models.Index(fields=['listing_id', 'event_name', 'occurred_at'], name='marketplace_listing_eb3274_idx'), models.Index(fields=['event_name', 'occurred_at'], name='marketplace_event_n_2e4955_idx')],
            },
        ),
        migrations.CreateModel(
            name='ListingAnalyticsState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing_id', models.BigIntegerField(db_index=True, unique=True)),
                ('buyer_user_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('seller_user_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('has_messaging_interaction', models.BooleanField(db_index=True, default=False)),
                ('first_messaging_at', models.DateTimeField(blank=True, null=True)),
                ('is_transaction_completed', models.BooleanField(db_index=True, default=False)),
                ('transaction_completed_at', models.DateTimeField(blank=True, null=True)),
                ('last_event_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['listing_id'],
                'indexes': [models.Index(fields=['has_messaging_interaction', 'is_transaction_completed'], name='marketplace_has_mes_1c2d17_idx'), models.Index(fields=['updated_at'], name='marketplace_updated_d0f833_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='analyticsevent',
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(buyer_user_id__isnull=True)
                    | models.Q(seller_user_id__isnull=True)
                    | ~models.Q(buyer_user_id=models.F('seller_user_id'))
                ),
                name='analytics_event_buyer_seller_not_equal_when_both_present',
            ),
        ),
    ]
