# Generated by Django 6.0.4 on 2026-04-09 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace_analytics', '0005_fix_named_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessagingResponseEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(choices=[('messages_screen_opened', 'Messages Screen Opened'), ('message_sent', 'Message Sent'), ('seller_avg_response_time', 'Seller Avg Response Time'), ('first_message_sent', 'First Message Sent')], db_index=True, max_length=50)),
                ('user_id', models.BigIntegerField(db_index=True)),
                ('seller_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('avg_response_minutes', models.FloatField(blank=True, help_text='Average response time in minutes', null=True)),
                ('unread_conversations', models.IntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('ingested_at', models.DateTimeField(auto_now_add=True)),
                ('properties', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-timestamp', '-id'],
                'indexes': [models.Index(fields=['event_name', 'timestamp'], name='bq4_event_time_idx'), models.Index(fields=['seller_id', 'timestamp'], name='bq4_seller_time_idx'), models.Index(fields=['user_id'], name='bq4_user_idx')],
            },
        ),
    ]
