# Generated by Django 6.0.4 on 2026-04-27 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace_analytics', '0006_messagingresponseevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampusLocationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(choices=[
                    ('campus_banner_shown', 'Campus Banner Shown'),
                    ('meeting_point_suggested', 'Meeting Point Suggested'),
                    ('location_detected', 'Location Detected')
                ], db_index=True, max_length=50)),
                ('user_id', models.BigIntegerField(db_index=True)),
                ('listing_id', models.BigIntegerField(null=True, blank=True, db_index=True)),
                ('seller_id', models.BigIntegerField(null=True, blank=True, db_index=True)),
                ('building_name', models.CharField(max_length=100, db_index=True)),
                ('latitude', models.FloatField(null=True, blank=True)),
                ('longitude', models.FloatField(null=True, blank=True)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('ingested_at', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(default=dict, blank=True)),
            ],
            options={
                'ordering': ['-timestamp', '-id'],
                'indexes': [
                    models.Index(fields=['event_name', 'timestamp'], name='bq10_event_time_idx'),
                    models.Index(fields=['building_name', 'timestamp'], name='bq10_building_time_idx'),
                    models.Index(fields=['user_id'], name='bq10_user_idx'),
                ],
            },
        ),
    ]
