# Generated by Django 6.0.4 on 2026-04-27 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace_analytics', '0007_campuslocationevent'),
        ('marketplace_analytics', '0007_crashevent'),
    ]

    operations = [
    ]
