# Generated by Django 6.0.3 on 2026-05-13 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace_analytics', '0007_crashevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyticsevent',
            name='event_name',
            field=models.CharField(db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='analyticsevent',
            name='listing_id',
            field=models.BigIntegerField(db_index=True, default=0),
        ),
    ]
